TEST_CATALOG = {
"Concrete": [
{"name":"Slump Test","type":"Fresh / Workability","destructive":False,"purpose":"Measures consistency/workability of fresh concrete by slump after removing the slump cone.","principle":"A compacted fresh-concrete cone is lifted vertically and the loss in height is measured.","apparatus":["Slump cone","Tamping rod","Base plate","Scale"],"procedure":["Moisten apparatus and place cone on a level base.","Fill in equal layers and rod each layer uniformly.","Strike off the top surface.","Lift the cone vertically without disturbing the concrete.","Measure the vertical difference between the cone height and displaced concrete height."],"result":"Report slump in mm and describe true, shear or collapse slump.","formula":"Slump = mould height − average height of slumped concrete","standard":"IS 1199 (fresh concrete methods)","notes":"Not suitable for every mix; very stiff or highly flowable mixes may need another workability test."},
{"name":"Compaction Factor Test","type":"Fresh / Workability","destructive":False,"purpose":"Determines workability of fresh concrete, especially for mixes of low workability.","principle":"Ratio of partially compacted concrete mass to fully compacted concrete mass.","apparatus":["Compaction-factor apparatus","Trowel","Balance","Cylinder"],"procedure":["Fill the upper hopper without compaction.","Open the first gate and allow concrete to fall into the lower hopper.","Open the second gate and allow it into the cylinder.","Strike off and weigh partially compacted concrete.","Empty, refill and fully compact the cylinder; weigh it."],"result":"Report compaction factor as a dimensionless ratio.","formula":"CF = mass of partially compacted concrete / mass of fully compacted concrete","standard":"IS 1199","notes":"Lower values generally indicate lower workability."},
{"name":"Vee-Bee Consistometer Test","type":"Fresh / Workability","destructive":False,"purpose":"Measures workability of stiff concrete using remoulding time under vibration.","principle":"Time required for a slump-shaped concrete sample to become cylindrical under vibration.","apparatus":["Vee-Bee consistometer","Slump cone","Transparent disc","Vibrator"],"procedure":["Prepare concrete in the slump cone inside the cylindrical container.","Lift cone and place transparent disc on concrete.","Start vibration and measure time until the concrete is fully remoulded."],"result":"Vee-Bee time in seconds.","formula":"Vee-Bee time = elapsed time for complete remoulding","standard":"IS 1199","notes":"Useful for low-workability concrete."},
{"name":"Flow Table Test","type":"Fresh / Workability","destructive":False,"purpose":"Measures flow of highly workable concrete.","principle":"Fresh concrete spread after controlled jolting is measured as flow.","apparatus":["Flow table","Mould","Tamping rod","Calipers"],"procedure":["Place and compact concrete in mould.","Lift mould vertically.","Apply prescribed table drops/jolts.","Measure spread in specified directions."],"result":"Report average flow/spread.","formula":"Flow percentage = (average spread − initial mould diameter)/initial mould diameter × 100","standard":"IS 1199","notes":"Particularly useful where slump is insensitive to changes in highly workable mixes."},
{"name":"Air Content Test","type":"Fresh / Air content","destructive":False,"purpose":"Determines air entrained or entrapped in fresh concrete.","principle":"Pressure or volumetric methods relate measured air volume to total concrete volume.","apparatus":["Air meter","Pressure vessel","Balance or calibrated container"],"procedure":["Fill and compact the measured concrete sample.","Seal the apparatus.","Apply the specified pressure or use the volumetric procedure.","Read and correct the air-content value as required."],"result":"Air content as percentage by volume.","formula":"Report measured air content after required aggregate correction.","standard":"Applicable fresh-concrete air-content method","notes":"Follow the exact apparatus standard because pressure and volumetric procedures differ."},
{"name":"Bleeding Test","type":"Fresh / Stability","destructive":False,"purpose":"Measures tendency of water to rise to the surface of fresh concrete.","principle":"Collected surface water is measured with time under controlled conditions.","apparatus":["Container","Graduated pipette/cylinder","Cover and balance"],"procedure":["Place a representative fresh-concrete sample in the specified container.","Keep under controlled conditions.","Remove and measure accumulated bleed water at prescribed intervals.","Report cumulative bleeding and rate if required."],"result":"Bleed-water volume or percentage and bleeding rate.","formula":"Bleeding (%) = mass/volume of bleed water relative to specified concrete sample basis.","standard":"Use the applicable fresh-concrete bleeding method.","notes":"Excessive bleeding can cause weak surface zones and poor bond."},
{"name":"Compressive Strength Test","type":"Hardened / Strength","destructive":True,"purpose":"Determines compressive strength of concrete specimens.","principle":"A specimen is loaded axially until failure and maximum load is divided by loaded area.","apparatus":["Compression testing machine","Cube/cylinder specimens","Calipers"],"procedure":["Prepare, cure and inspect specimen.","Measure dimensions and calculate loaded area.","Center specimen in the testing machine.","Apply load at the prescribed rate until failure.","Record maximum load and calculate strength."],"result":"Compressive strength in MPa.","formula":"f_c = P/A","standard":"IS 516 (Part 1/Sec 1):2021","notes":"Failure pattern and specimen condition should also be recorded."},
{"name":"Split Tensile Strength Test","type":"Hardened / Strength","destructive":True,"purpose":"Estimates tensile strength of concrete by diametral compression of a cylinder.","principle":"Compression along a diameter produces an approximately uniform tensile stress perpendicular to the load.","apparatus":["Compression testing machine","Cylindrical specimen","Packing strips where specified"],"procedure":["Measure specimen dimensions.","Align cylinder horizontally in the testing machine.","Apply load continuously at prescribed rate until splitting occurs.","Record maximum load."],"result":"Indirect tensile strength in MPa.","formula":"f_ct = 2P/(πLD)","standard":"IS 516 (Part 1/Sec 1):2021","notes":"This is an indirect tensile test, not a direct tension test."},
{"name":"Flexural Strength Test","type":"Hardened / Strength","destructive":True,"purpose":"Determines flexural strength/modulus of rupture of concrete beams.","principle":"A beam is loaded in bending until failure and flexural strength is calculated from failure load and geometry.","apparatus":["Flexural testing machine","Beam specimen","Loading arrangement"],"procedure":["Measure specimen dimensions and span.","Place beam correctly on supports.","Apply load using the prescribed loading arrangement.","Record failure load and failure location.","Calculate flexural strength using the applicable equation."],"result":"Flexural strength in MPa.","formula":"Use the equation corresponding to the specified loading and failure location.","standard":"IS 516 (Part 1/Sec 1):2021","notes":"Do not mix equations for different loading arrangements."},
{"name":"Concrete Core Test","type":"Hardened / In-situ strength","destructive":True,"purpose":"Obtains cores from existing concrete for direct laboratory testing and assessment.","principle":"A cylindrical core is drilled from the structure, prepared and tested in compression or other applicable tests.","apparatus":["Core drilling machine","Diamond bit","Measuring tools","Testing machine"],"procedure":["Select representative core locations avoiding reinforcement where appropriate.","Drill and extract core carefully.","Measure, condition and prepare ends as specified.","Test core and record dimensions, orientation and condition.","Apply required corrections/interpretation from the governing standard."],"result":"Core strength and specimen information.","formula":"Compressive stress = maximum load / corrected loaded area, with applicable standard corrections.","standard":"IS 516 (Part 4):2018","notes":"Core results are affected by location, moisture, orientation, drilling damage and size; interpretation should follow the standard."},
{"name":"Rebound Hammer Test","type":"Hardened / NDT","destructive":False,"purpose":"Assesses surface hardness/uniformity and provides an estimate of concrete strength when properly correlated.","principle":"A spring-driven mass rebounds from a concrete surface; rebound response is related to surface hardness.","apparatus":["Rebound hammer","Grinding stone","Calibration equipment"],"procedure":["Select representative, sound test locations.","Prepare surface and remove loose material.","Hold hammer perpendicular to the surface.","Take the prescribed number of readings and reject invalid readings per method.","Report rebound index and, where justified, correlated strength."],"result":"Rebound number/index; estimated strength only with suitable correlation.","formula":"No universal strength equation; use manufacturer/standard correlation appropriate to the concrete.","standard":"IS 516 (Part 5/Sec 4):2020","notes":"It is not a stand-alone proof of compressive strength."},
{"name":"Ultrasonic Pulse Velocity Test","type":"Hardened / NDT","destructive":False,"purpose":"Assesses concrete uniformity, continuity and quality and can help identify cracks/voids.","principle":"Pulse travel time through concrete is measured between transducers and converted to velocity.","apparatus":["UPV instrument","Transducers","Couplant","Measuring scale"],"procedure":["Select and prepare test path.","Apply couplant and place transducers in the specified arrangement.","Measure path length and pulse travel time.","Calculate pulse velocity and interpret with the standard and site conditions."],"result":"Pulse velocity in km/s plus qualitative assessment.","formula":"V = L/T","standard":"IS 516 (Part 5/Sec 1):2018","notes":"Moisture, temperature, aggregate type, reinforcement and path geometry influence readings."},
{"name":"Half-Cell Potential Test","type":"Hardened / NDT","destructive":False,"purpose":"Assesses likelihood of corrosion activity of embedded reinforcing steel.","principle":"Measures electrical potential of reinforcement relative to a reference electrode.","apparatus":["Half-cell electrode","High-impedance voltmeter","Electrical connection to reinforcement"],"procedure":["Expose/connect electrically to reinforcement at the test area.","Prepare concrete surface and establish required electrical continuity.","Take potential readings on a grid.","Map contours and interpret probability of corrosion using the applicable standard."],"result":"Potential map in mV and corrosion-likelihood interpretation.","formula":"Report measured electrode potential with reference electrode and conditions.","standard":"IS 516 (Part 5/Sec 2):2021","notes":"Potential indicates corrosion probability, not corrosion rate or steel loss directly."},
{"name":"Carbonation Depth Test","type":"Hardened / NDT","destructive":False,"purpose":"Measures depth of carbonation in exposed concrete.","principle":"Freshly exposed concrete is treated with phenolphthalein indicator; the carbonation front is identified by the colour response.","apparatus":["Freshly exposed concrete surface","Phenolphthalein solution","Scale/depth gauge"],"procedure":["Expose a fresh concrete surface or use a suitable fracture/core surface.","Apply phenolphthalein as specified.","Identify the carbonation front.","Measure depth at representative points."],"result":"Carbonation depth in mm.","formula":"Carbonation depth = surface-to-carbonation-front distance","standard":"IS 516 (Part 5/Sec 3):2021","notes":"The test assesses carbonation depth; it should not be used alone to diagnose reinforcement corrosion."},
{"name":"Water Penetration Under Pressure","type":"Hardened / Durability","destructive":False,"purpose":"Determines depth of water penetration under specified pressure.","principle":"Water is applied under pressure to a hardened concrete face and penetration depth is measured after splitting the specimen.","apparatus":["Water-pressure apparatus","Concrete specimens","Measuring scale"],"procedure":["Prepare and seal specimen as specified.","Apply water pressure for the specified duration.","Split specimen.","Measure maximum penetration depth at prescribed locations."],"result":"Maximum/characteristic penetration depth in mm.","formula":"Report penetration depth according to the standard.","standard":"IS 516 (Part 2/Sec 1):2018","notes":"Useful as a durability/permeability-related test, not a direct strength test."},
{"name":"Drying Shrinkage Test","type":"Hardened / Deformation","destructive":False,"purpose":"Measures length change of hardened concrete during drying.","principle":"Length change of a specimen is monitored between controlled reference conditions.","apparatus":["Shrinkage specimens","Length comparator","Controlled storage"],"procedure":["Cast and cure specimens according to the standard.","Measure initial reference length.","Store under specified drying conditions.","Take comparator readings at prescribed ages.","Calculate percentage length change."],"result":"Drying shrinkage/length change.","formula":"Shrinkage strain = change in length / gauge length","standard":"IS 516 (Part 6):2020","notes":"Control moisture and temperature carefully."},
{"name":"Static Modulus of Elasticity","type":"Hardened / Deformation","destructive":False,"purpose":"Determines static modulus and Poisson's ratio of concrete under compression.","principle":"Stress-strain response under specified loading cycles provides modulus and lateral strain response provides Poisson's ratio.","apparatus":["Compression testing machine","Strain gauges/extensometer","Concrete specimen"],"procedure":["Prepare and instrument specimen.","Apply specified loading cycles.","Record axial and lateral strains over the prescribed stress range.","Calculate modulus and Poisson's ratio."],"result":"Static modulus of elasticity and Poisson's ratio.","formula":"E = change in stress / corresponding change in strain over specified range.","standard":"IS 516 (Part 8/Sec 1):2020","notes":"Use the standard loading and strain ranges; modulus is not simply an assumed constant."}
],
"Cement": [
{"name":"Fineness by Dry Sieving","type":"Physical","destructive":False,"purpose":"Determines fineness of cement by retained residue on a specified sieve.","principle":"A representative cement sample is sieved and the retained mass is measured.","apparatus":["Specified sieve","Balance","Brush"],"procedure":["Take and weigh representative cement.","Sieve for the prescribed time.","Collect and weigh retained residue.","Calculate percentage residue."],"result":"Percentage residue.","formula":"Residue (%) = retained mass/sample mass × 100","standard":"IS 4031 (Part 1):1996","notes":"Use clean, dry apparatus and avoid loss of material."},
{"name":"Standard Consistency","type":"Physical","destructive":False,"purpose":"Determines water content required to prepare cement paste of standard consistency.","principle":"Penetration of the Vicat plunger into cement paste is used to identify the specified consistency.","apparatus":["Vicat apparatus","Plunger","Balance","Measuring cylinder"],"procedure":["Prepare cement paste with trial water percentages.","Fill Vicat mould and level surface.","Release plunger and observe penetration.","Adjust water until the specified penetration criterion is met."],"result":"Water percentage for standard consistency, P.","formula":"P = water mass/cement mass × 100","standard":"IS 4031 (Part 4):1988","notes":"This is used as a reference for other cement tests."},
{"name":"Initial and Final Setting Time","type":"Physical","destructive":False,"purpose":"Determines the time available for handling/placing and the time by which cement paste reaches specified setting conditions.","principle":"Vicat needle penetration is observed at controlled intervals.","apparatus":["Vicat apparatus","Needles","Stopwatch"],"procedure":["Prepare paste at standard consistency.","Fill mould and start timing.","Take penetration observations at prescribed intervals.","Record initial and final setting according to the specified penetration criteria."],"result":"Initial and final setting times.","formula":"Setting time = elapsed time from water addition to specified penetration criterion.","standard":"IS 4031 (Part 5):1988","notes":"Record time from the defined start point and maintain test conditions."},
{"name":"Soundness by Le Chatelier","type":"Physical","destructive":False,"purpose":"Assesses expansion tendency of cement due to certain expansive constituents.","principle":"Change in indicator distance after specified heating indicates expansion.","apparatus":["Le Chatelier apparatus","Water bath","Glass plates","Balance"],"procedure":["Prepare cement paste and fill mould.","Cover and condition as specified.","Heat in water under the prescribed regime.","Measure indicator separation before and after treatment."],"result":"Expansion in mm.","formula":"Soundness expansion = final indicator distance − initial distance","standard":"IS 4031 (Part 3):1988","notes":"Follow the exact conditioning and heating sequence."},
{"name":"Compressive Strength of Cement Mortar","type":"Strength","destructive":True,"purpose":"Determines compressive strength of standardized cement mortar specimens.","principle":"Standard mortar specimens are cured and loaded in compression to failure.","apparatus":["Standard sand","Moulds","Compression testing machine","Curing tank"],"procedure":["Prepare mortar with prescribed proportions.","Fill and compact moulds.","Cure specimens for specified ages.","Test in compression and record maximum load.","Calculate strength."],"result":"Compressive strength in MPa.","formula":"Strength = maximum load / loaded area","standard":"IS 4031 (Part 6):1988","notes":"Use the specified sand, mixing, curing and loading procedure."}
],
"Aggregates": [
{"name":"Sieve Analysis","type":"Gradation","destructive":False,"purpose":"Determines particle-size distribution and grading of fine or coarse aggregate.","principle":"Aggregate is separated through a stack of sieves and retained masses are measured.","apparatus":["Set of sieves","Balance","Mechanical shaker"],"procedure":["Dry representative sample.","Arrange sieves in descending aperture size.","Place sample and sieve for prescribed duration.","Weigh retained material on each sieve.","Calculate percentages and grading parameters."],"result":"Percentage retained/passing and grading curve.","formula":"Cumulative % retained = sum of retained percentages up to sieve; % passing = 100 − cumulative % retained","standard":"Applicable IS aggregate test method","notes":"Representative sampling is essential."},
{"name":"Aggregate Crushing Value","type":"Mechanical","destructive":True,"purpose":"Measures resistance of aggregate to crushing under gradually applied compressive load.","principle":"Percentage of fines produced from a standard aggregate sample under specified load indicates crushing resistance.","apparatus":["ACV cylinder and plunger","Compression testing machine","Sieves","Balance"],"procedure":["Prepare aggregate fraction as specified.","Fill cylinder and apply the specified compaction.","Apply prescribed load.","Sieve crushed material.","Determine mass of fines."],"result":"Aggregate crushing value in percent.","formula":"ACV = mass of fines / original sample mass × 100","standard":"IS 2386 (Part 4):1963","notes":"Lower value generally indicates greater resistance to crushing."},
{"name":"Aggregate Impact Value","type":"Mechanical","destructive":True,"purpose":"Measures resistance of aggregate to sudden impact.","principle":"A standard aggregate sample is subjected to repeated blows and the resulting fines are measured.","apparatus":["Impact testing machine","Cylindrical cup","Hammer","Sieves","Balance"],"procedure":["Prepare specified aggregate fraction.","Place in cup and compact as required.","Apply the prescribed number of blows.","Sieve and weigh fines."],"result":"Impact value in percent.","formula":"AIV = mass of fines / original sample mass × 100","standard":"IS 2386 (Part 4):1963","notes":"Used as an indication of toughness under impact."},
{"name":"Los Angeles Abrasion Test","type":"Mechanical","destructive":True,"purpose":"Measures resistance of aggregate to abrasion and impact in a rotating drum.","principle":"Aggregate and specified abrasive charge rotate together; mass loss indicates abrasion resistance.","apparatus":["Los Angeles abrasion machine","Steel spheres","Sieves","Balance"],"procedure":["Select aggregate grading and charge.","Place sample and abrasive charge in drum.","Rotate for prescribed revolutions.","Sieve the material and determine loss."],"result":"Percentage loss.","formula":"Abrasion loss (%) = mass loss / original mass × 100","standard":"IS 2386 (Part 4):1963","notes":"The test grading and charge depend on the specified procedure."},
{"name":"Aggregate Water Absorption","type":"Physical","destructive":False,"purpose":"Determines water absorption and helps assess porosity/quality of aggregate.","principle":"Mass difference between saturated surface-dry and oven-dry states represents absorbed water.","apparatus":["Oven","Balance","Wire basket/tray"],"procedure":["Oven-dry sample to constant mass.","Cool and weigh dry mass.","Soak for specified period.","Bring to saturated surface-dry condition and weigh.","Calculate absorption."],"result":"Water absorption percentage.","formula":"Absorption (%) = (SSD mass − dry mass)/dry mass × 100","standard":"IS 2386 (Part 3):1963","notes":"Moisture condition definitions must be followed carefully."}
],
"Bricks & Blocks": [
{"name":"Compressive Strength of Brick","type":"Strength","destructive":True,"purpose":"Determines compressive strength of masonry bricks.","principle":"Prepared brick specimen is loaded in compression until failure.","apparatus":["Compression testing machine","Capping/packing materials as specified","Balance and measuring tools"],"procedure":["Prepare specimen according to the standard.","Measure loaded area.","Center in machine.","Apply load uniformly until failure.","Calculate compressive strength."],"result":"Compressive strength in N/mm².","formula":"Strength = maximum load / loaded area","standard":"Applicable IS brick test method","notes":"Preparation and moisture conditioning affect results."},
{"name":"Water Absorption of Brick","type":"Physical","destructive":False,"purpose":"Determines percentage water absorption of brick after immersion.","principle":"Increase in mass after specified immersion is compared with dry mass.","apparatus":["Oven","Balance","Water tank"],"procedure":["Dry brick to constant mass.","Cool and weigh.","Immerse for specified duration.","Remove, wipe surface and weigh.","Calculate absorption."],"result":"Water absorption percentage.","formula":"Absorption (%) = (wet mass − dry mass)/dry mass × 100","standard":"Applicable IS brick specification/test method","notes":"Use the conditioning period and weighing method required by the relevant product standard."},
{"name":"Efflorescence Test","type":"Durability / Appearance","destructive":False,"purpose":"Assesses tendency of masonry units to develop soluble salt deposits on the surface.","principle":"Controlled wetting and drying allows soluble salts to migrate and deposit.","apparatus":["Flat non-absorbent tray","Water","Controlled test environment"],"procedure":["Place specimens in the specified shallow water condition.","Allow capillary absorption and drying as specified.","Repeat/observe the required cycles.","Assess deposited salts using the grading criteria."],"result":"Efflorescence class/description.","formula":"Qualitative classification according to applicable standard.","standard":"Applicable IS brick test method","notes":"Salt source may be brick, mortar, water or surrounding materials."}
],
"Steel": [
{"name":"Tensile Test of Reinforcement Steel","type":"Mechanical","destructive":True,"purpose":"Determines yield/proof stress, ultimate tensile strength, elongation and related tensile properties.","principle":"A standardized steel specimen is loaded in tension until fracture while load and elongation are measured.","apparatus":["Universal testing machine","Extensometer","Steel specimen"],"procedure":["Measure specimen dimensions/gauge length.","Grip specimen centrally.","Apply tensile load at prescribed rate.","Record yield/proof behavior, maximum load and elongation.","Calculate stresses and elongation."],"result":"Yield/proof stress, tensile strength, elongation and stress-strain behavior.","formula":"Stress = load/original area; engineering strain = extension/original gauge length","standard":"Applicable steel product standard and tensile-test method","notes":"Use the product grade standard for acceptance criteria."},
{"name":"Bend Test","type":"Mechanical","destructive":True,"purpose":"Checks ductility and soundness of steel by bending a specimen around a prescribed former.","principle":"Specimen is bent through a specified angle/radius and examined for cracks.","apparatus":["Bending machine/fixture","Specified former"],"procedure":["Prepare specimen as specified.","Place over former.","Apply load and bend through required angle.","Inspect the tension surface for cracks or defects."],"result":"Pass/fail and observed defects.","formula":"Bending radius/angle according to product standard.","standard":"Applicable steel product standard","notes":"Acceptance criteria depend on grade and diameter/thickness."},
{"name":"Ultrasonic Testing of Steel","type":"NDT","destructive":False,"purpose":"Detects internal discontinuities in steel members or welds.","principle":"Ultrasonic waves reflect from interfaces/discontinuities and are received by a transducer.","apparatus":["Ultrasonic flaw detector","Probe/transducer","Couplant","Calibration block"],"procedure":["Calibrate instrument with suitable reference block.","Prepare surface and apply couplant.","Scan the examination zone in prescribed directions.","Interpret echoes against acceptance criteria."],"result":"Indication location/amplitude and acceptance classification.","formula":"Depth/location derived from calibrated sound path and instrument settings.","standard":"Use applicable steel/weld NDT standard and project acceptance criteria.","notes":"Interpretation requires trained personnel."}
],
"Soil": [
{"name":"Grain Size Analysis","type":"Index / Classification","destructive":False,"purpose":"Determines particle-size distribution of soil.","principle":"Coarser particles are separated by sieving and finer fractions by sedimentation methods.","apparatus":["Sieves","Balance","Hydrometer where applicable","Sedimentation cylinder"],"procedure":["Prepare representative soil sample.","Separate coarse fraction by sieving.","For fine fraction, disperse and perform sedimentation/hydrometer procedure where required.","Calculate percentage passing."],"result":"Particle-size distribution curve and percentages.","formula":"% passing = 100 − cumulative % retained for sieve fraction; sedimentation uses Stokes-based interpretation under the applicable method.","standard":"Applicable IS soil test methods","notes":"Dispersant, temperature and specific gravity corrections matter for hydrometer work."},
{"name":"Atterberg Limits","type":"Index","destructive":False,"purpose":"Determines liquid limit, plastic limit and plasticity characteristics of fine-grained soil.","principle":"Consistency changes with water content are measured using standardized procedures.","apparatus":["Liquid-limit device or cone apparatus","Glass plate","Balance","Oven"],"procedure":["Prepare representative fine soil fraction.","Determine liquid limit using the specified method.","Roll soil threads for plastic limit until the criterion is reached.","Calculate plasticity index."],"result":"LL, PL and PI.","formula":"PI = LL − PL","standard":"Applicable IS 2720 Part 5 method","notes":"Use the same prescribed liquid-limit method consistently."},
{"name":"Standard Proctor Compaction Test","type":"Compaction","destructive":False,"purpose":"Determines optimum moisture content and maximum dry density under standard compaction energy.","principle":"Dry density is measured at several water contents after standardized compaction.","apparatus":["Proctor mould","Ram mer","Balance","Oven"],"procedure":["Prepare soil at different moisture contents.","Compact each specimen with prescribed energy.","Determine bulk and dry density.","Plot dry density versus water content.","Identify peak dry density and corresponding OMC."],"result":"MDD and OMC.","formula":"Dry density = bulk density/(1+w); OMC occurs at maximum dry density on the curve.","standard":"Applicable IS 2720 compaction method","notes":"Compactive effort must be stated."},
{"name":"Direct Shear Test","type":"Strength","destructive":True,"purpose":"Determines shear strength parameters of soil under controlled normal stress.","principle":"Soil in a shear box is forced to shear along a predefined plane while horizontal load and displacement are measured.","apparatus":["Direct shear box","Loading frame","Dial gauges","Proving ring/load cell"],"procedure":["Prepare and place specimen.","Apply selected normal stress.","Shear at prescribed displacement rate.","Record shear stress and displacement.","Repeat at different normal stresses and determine strength envelope."],"result":"Cohesion/intercept and friction angle for the test condition.","formula":"τ_f = c + σ'_n tan φ' for effective-stress interpretation where applicable.","standard":"Applicable IS 2720 shear-strength method","notes":"Drainage and rate conditions must be clearly specified."}
]
}

TEST_CATEGORIES = [
"Concrete","Cement","Aggregates","Bricks & Blocks","Steel","Soil"
]

def list_tests(category="", test_type=""):
    items = TEST_CATALOG.get(category, []) if category else [x for v in TEST_CATALOG.values() for x in v]
    if test_type:
        items = [x for x in items if test_type.lower() in x.get("type","").lower()]
    return items

def get_test(category, name):
    for item in TEST_CATALOG.get(category, []):
        if item["name"].lower() == name.lower():
            return item
    return None
